version: 1.0.{build}

# Operating system (build VM template)
os: Visual Studio 2015 CTP

environment:
  matrix:
    - VS_VERSION: MSVC2015

build_script:
  - ruby -ropenssl -e 'puts OpenSSL::OPENSSL_VERSION'
  - curl -O http://curl.haxx.se/ca/cacert.pem
  - echo %cd%
  - SET SSL_CERT_FILE=%cd%\cacert.pem
  - echo %SSL_CERT_FILE%
  - ruby -ropen-uri -e 'eval open("https://rubygems.org").read'
  
  - git submodule update --init --recursive
  - bundle install --verbose
  - vcbuild.bat %VS_VERSION%

test_script:
  - vcbuild.bat %VS_VERSION% test
  - vcbuild.bat %VS_VERSION% inttest
