version: 1.0.{build}

# Operating system (build VM template)
os: Visual Studio 2015 CTP

environment:
  matrix:
    - VS_VERSION: MSVC2015

build_script:
  - gem install bundler 
  - gem update --system
  - git submodule update --init --recursive
#  - ruby -ropen-uri -e 'eval open("https://rubygems.org").read'
  - bundle install
  - vcbuild.bat %VS_VERSION%

test_script:
  - vcbuild.bat %VS_VERSION% test
  - vcbuild.bat %VS_VERSION% inttest
