version: 1.0.{build}

# Operating system (build VM template)
os: Visual Studio 2015 CTP

environment:
  matrix:
    - VS_VERSION: MSVC2015

build_script:
  - curl -O https://rubygems.org/gems/rubygems-update-2.7.7.gem
  - gem install --local rubygems-update-2.7.7.gem
  - update_rubygems
  - git submodule update --init --recursive
#  - ruby -ropen-uri -e 'eval open("https://rubygems.org").read'
  - bundle install
  - vcbuild.bat %VS_VERSION%

test_script:
  - vcbuild.bat %VS_VERSION% test
  - vcbuild.bat %VS_VERSION% inttest
