# Operating system (build VM template)
os: Visual Studio 2015 CTP

environment:
  matrix:
    - VS_VERSION: MSVC2015

install:
  - set PATH=C:\Ruby22\bin;%PATH%

build_script:
  - curl -O https://curl.haxx.se/ca/cacert.pem
  - SET SSL_CERT_FILE=%cd%\cacert.pem
  
  - git submodule update --init --recursive
  - bundle install
  - vcbuild.bat %VS_VERSION%

test_script:
  - vcbuild.bat %VS_VERSION% test
  - vcbuild.bat %VS_VERSION% inttest
